services:
  crm-frontend:
    image: crm-frontend:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.crm-frontend.rule=Host(`painel.inoovaweb.com.br`)"
        - "traefik.http.routers.crm-frontend.entrypoints=websecure"
        - "traefik.http.routers.crm-frontend.tls=true"
        - "traefik.http.routers.crm-frontend.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.crm-frontend.loadbalancer.server.port=80"
    networks:
      - inoovawebpro

  crm-backend:
    image: crm-backend:latest
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    env_file:
      - backend/.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.crm-backend.rule=Host(`api-crminoovaweb.inoovaweb.com.br`)"
        - "traefik.http.routers.crm-backend.entrypoints=websecure"
        - "traefik.http.routers.crm-backend.tls=true"
        - "traefik.http.routers.crm-backend.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.crm-backend.loadbalancer.server.port=3001"
    networks:
      - crm_network
      - inoovawebpro

  redis:
    image: redis:7-alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - crm_network

networks:
  crm_network:
    driver: overlay
    attachable: true
  inoovawebpro:
    external: true
